name: Add labels

on:
  workflow_dispatch:
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display PRs
        with:
          script: |
            for pr in api.pulls.list():
                log.display(pr=pr)
      - uses: ./.github/actions/pyactions
        name: Trigger test workflow on PRs
        env:
          GITHUB_TOKEN: ${{ secrets.PYACTIONS_TOKEN }}
        with:
          script: |
            trigger = LabelAddTrigger("CI:run")
            for pr in api.pulls.list():
                log.display(pr=pr)
                trigger.emit(api, target=pr, reset_now=False)


