name: Assign matrix

on:
  workflow_dispatch:
    inputs:

      project-id:
        description: Project ID
        required: true
        type: choice
        options:
        - idaes
        - watertap
        - dispatches

      python-version:
        description: Python version
        type: choice
        options:
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        required: false
        default: '3.9'

jobs:

  vars:
    runs-on: ubuntu-latest
    outputs:
      project-id: ${{ matrix.project-id }}
      repository: ${{ matrix.repository }}
      pypi-name: ${{ matrix.pypi-name }}
      test-command: ${{ matrix.test-command }}
      matrix: ${{ toJSON(matrix) }}
      strategy: ${{ toJSON(strategy) }}
    strategy:
      fail-fast: true
      matrix:
        project-id:
        - ${{ inputs.project-id }}
        include:
        - project-id: idaes
          repository: IDAES/idaes-pse
          pypi-name: idaes-pse
          test-command: |
            idaes get-extensions --extra petsc --verbose
            pip install pytest
            wget https://raw.githubusercontent.com/IDAES/idaes-pse/main/pytest.ini
            pytest --pyargs idaes -m "unit" -x
    steps:
    - name: Do nothing
      run: sleep 1

  other-job:
    name: Other job for ${{ needs.vars.outputs.project-id }}
    runs-on: ubuntu-latest
    needs: [vars]
    strategy: ${{ fromJSON(needs.vars.outputs.strategy) }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          repository: ${{ matrix.repository }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install ${{ matrix.pypi-name }}
        run: |
          pip install --progress-bar off "${{ matrix.pypi-name }}"
      - name: Run test command
        run: |
          ${{ matrix.test-command }}
