name: Post Integration

on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
    # branches-ignore:
    #   - main

jobs:
  reset_triggers:
    name: Reset integration triggers
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.pull_requests[0] != null
    if: contains(github.event.workflow_run.event, 'pull_request')
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display contexts
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        with:
          script: |
            log.display(github=github)
            log.display(github__event=github.event)
      - uses: ./.github/actions/pyactions
        name: Reset trigger
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          GITHUB_TOKEN: ${{ secrets.PYACTIONS_TOKEN }}
        with:
          script: |
            log.display(context_github=context_github)
            run_data = github.event.workflow_run
            log.display(run_data=run_data)
            prs = run_data.pull_requests
            if not prs:
                prs = [
                    pr for pr in api.pulls.list()
                    if pr.head.sha == run_data.head_sha
                ]
            log.info(f'{len(prs)}')
            trigger = LabelAddTrigger("CI:run")
            for pr in prs:
                log.display(pr=pr) 
                trigger.reset(api, target=pr)
