name: Refmatrix

on:
  workflow_call:
    inputs:
      repository:
        description: Repository to check out, in format <owner>/<name>
        type: string
        required: true
      refs-json:
        description: JSON string specifying list of Git refs to be used
        type: string
        default: ''
        required: false

jobs:

  trial:
    name: ${{ inputs.repository }} (ref=${{ matrix.ref }}, runner=${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: False
      matrix:
        ref: ${{ fromJSON(inputs.refs-json) }}
        runner: ${{ fromJSON(vars.runners_json || '["ubuntu-latest"]') }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ matrix.ref }}
          fetch-depth: 0
      - name: Stand-in for the actual step(s) to run
        run: git log -n 1

  sample-pytest:
    uses: ./.workflows/sample-pytest.yml
    strategy:
      fail-fast: False
      matrix:
        ref: ${{ fromJSON(inputs.refs-json) }}
        os: [linux, win64, macos]
        py: ['3.7', '3.10']
    with:
      repository: ${{ inputs.repository }}
      python-distr-name: watertap
      ref: ${{ matrix.ref }}
      os: ${{ matrix.os }}
      python-version: ${{ matrix.py }}
