name: Test running on self-hosted worker

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Create Conda env and install a package
        run: |
          conda create --yes --name gh-wf-env python=3.8 pip
          conda activate gh-wf-env
          which python
          pip install proteuslib pytest coverage pytest-cov
          wget https://raw.githubusercontent.com/nawi-hub/proteuslib/main/pytest.ini
          pytest --pyargs proteuslib
